[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Exclude node_modules from deploy
[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "18" 